### ISSUE TITLE
Improve/Refactor Dependency Watchdog (v2)

### ISSUE THREAD

**Issue by ashwani2k** [gardener/dependency-watchdog#53]
# Stories
- As developer I want a robust, scalable, and maintainable code base, so that issues are minimised and maintenance effort improves.

# Motivation
We made the following observations:
- Bringing down KCM when it's not required #35
- Inability to handle kubeconfig rotation for all edge scenarios #36
- Lack of Test automation to be able to release with confidence (current code coverage of prober is 9%)
- Just keeping the code base updated with evolution of Kubernetes for e.g. adapting to stories around https://github.com/gardener/gardener/issues/4251
- As a developer the current code base also is pretty convoluted to maintain and requires sufficient efforts for someone new to make headway into the code.

All these observations, when put together, make it apparent that the fixes provided in the recent past are more band-aids that will back-fire with more and more Gardener adoption. DWD, being a critical component for the health of the Gardener-managed control planes, should be redesigned/refactored/refined/adapted to improve robustness, scalability, and maintainance effort.

# Acceptance Criteria
- [ ] Documentation/Proposal
  - [x] Create a design document for prober
  - [x] Enhance the design to include weeder which was previously called endpoint command
  - [x] Re-structure README and create multiple markdown files which the consumers can reference
  - [ ] Add example configurations for weeder and prober

- [x] Prober
  - [x] Implement new Prober design
  - [x] Write Unit tests - target 90%+ functional coverage
  - [x] Programmatically bring up a vanilla KIND cluster for unit tests
  - [x] Look at all Open/Close issues on DWD w.r.t prober and verify that all issues are fixed in the new code
  - [x] Work on gardener PR for https://github.com/gardener/gardener/issues/5878

- [ ] Weeder
  - [x] Finalize the new design
  - [x] Implement new weeder design
  - [x] Unit and integration tests - target 90% functional coverage
  - [x] Look at all Open/Close issues on DWD w.r.t weeder and verify that all issues are fixed in the new code
  - [ ] Work on gardener PR for https://github.com/gardener/gardener/issues/5878

- [ ] CI/CD
  - [x] Configure Prow jobs for dependency watchdog
  - [x] Enhance the Makefile and add necessary scripts under `/hack` (take inspiration from g/g)
  - [x] Identify tools that are required for make targets and create a `tools.mk` for it.

- [ ] Metrics
  - [ ] Identify metrics that should be exposed out of prober/weeder
  - [ ] Identify the dashboard on Graphana where these metrics will be pushed and create relevant graphs/charts.

- [ ] Botanist: Configuration change Issue/PR
  - [ ] Create an issue on gardener/gardener and raise a PR to change the prober configuration in operations/botanist

# Enhancement/Implementation Proposal (optional)
- Relook at how we can add more components to the dependency graph of resources as well as how we can handle secret rotation (https://github.com/gardener/dependency-watchdog/issues/38).
- We should capture the change in a proposal doc which can be shared with interested parties and community at large.
- We should do a community demo to showcase and share the change and its benefits with the community.

**Comment by unmarshall** [comment]
There is currently no need to write integration tests as many of the unit tests are written either using `envtest` testing framework provided by `controller-runtime` or by programmatically starting a vanilla `KIND cluster`. All functional cases are currently covered and integration tests are not going to provide any additional value.

**Comment by ashwani2k** [comment]
As we are getting ready for release we also need to take care of followin -- 
- [ ] Adapt the README.md file for - 
  - [ ] Usage for local development 
  - [ ] Usage for contribution like guideline for test/qualification before requesting for change
- [ ] Usage doc for end-user with example of config this can be then linked to gardener usage doc. 
  - [ ] Create a docforge.yaml for this release to make it easy to consume from gardener.cloud documentation.  
- [ ] New Design/Flow for endpoint prober which will be now known as `weeder`
- [ ] New Design/Flow for prober part. The original README doesn't talk about prober. 
- [ ] Upgrade path from v1 to v2 (do's and don't)

**Comment by ashwani2k** [comment]
Can we include https://github.com/gardener/dependency-watchdog/issues/63 feature request as well with this release.
